spring:
  application:
    name: service-registory

eureka:
  instance:
    hostname: ims-discovery-server.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ims-db-service.herokuapp.com/eureka/